# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f161cdd2958103ee2d59e2d85c21c05931b0efe3398bb6f6268f9060cd05e9228ec839837f297c1d95e84353fa65e3957ec1343dad393cfae8c0e5ea99f3de2

test:
  secret_key_base: 876ccfd6b09bcf24a44a7a658f0add527b1d13e245bf795ef23e0756a390311b7d8fd7c2f30756460c10b7fff99a0c05adca56aaa289c9fb8badb74def1f7345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
